org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
android.useAndroidX=true
org.gradle.configuration-cache=false
systemProp.http.proxyHost=proxy.example.com
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=proxy.example.com
systemProp.https.proxyPort=7890
systemProp.http.nonProxyHosts=localhost|127.0.0.1
